name: Testing with selenium Java

on:
  push:
    branches: ["main"]
    pull_request:
      branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses : actions/checkout@v4

      - name : Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

            - uses: browser-actions/setup-chrome@v1
            - run: chrome --version

            - name: Run Selenium Tests
              run: mvn clean test

            - name: Test Report
              uses: actions/upload-artifact@v4
              with:
                name: my-artifact
                path: reports

